# 开发的时候，指定为dev或者local即可。发布时候，通过-Dspring.cloud.config.profile来指定真正的profile
spring:
  profiles:
    active: dev
thymeleaf:
  prefix: classpath:/templates
  cache: false
  suffix: .html
  encoding: UTF-8
  content-type: text/html

server:
  port: 10000